export default [
  {
    name: 'BreakFast',
    entries: [
      {
        name: 'pancakes',
        quantity: 1,
        calories: 350,
        carbs: 50,
        fat: 10,
        protein: 8,
      },
      {
        name: 'scrambled eggs',
        quantity: 1,
        calories: 200,
        carbs: 2,
        fat: 15,
        protein: 14,
      },
      {
        name: 'bacon',
        quantity: 1,
        calories: 150,
        carbs: 0,
        fat: 12,
        protein: 10,
      },
      {
        name: 'toast',
        quantity: 1,
        calories: 100,
        carbs: 20,
        fat: 2,
        protein: 3,
      },
    ],
  },
  {
    name: 'Lunch',
    entries: [
      {
        name: 'yogurt',
        quantity: 1,
        calories: 120,
        carbs: 15,
        fat: 4,
        protein: 6,
      },
      {
        name: 'granola bar',
        quantity: 1,
        calories: 200,
        carbs: 30,
        fat: 7,
        protein: 5,
      },
      {
        name: 'bagel with cream cheese',
        quantity: 1,
        calories: 300,
        carbs: 50,
        fat: 10,
        protein: 8,
      },
    ],
  },
  {
    name: 'Dinner',
    entries: [
      {
        name: 'grilled chicken breast',
        calories: 220,
        quantity: 1,
        carbs: 0,
        fat: 5,
        protein: 40,
      },
      {
        name: 'vegetable stir-fry',
        quantity: 1,
        calories: 250,
        carbs: 45,
        fat: 10,
        protein: 7,
      },
      {
        name: 'quinoa and black beans',
        quantity: 1,
        calories: 350,
        carbs: 60,
        fat: 10,
        protein: 12,
      },
    ],
  },
];
